//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprwMusic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRW_USER
    {
        public SPRW_USER()
        {
            this.SPRW_ARTIST_MEMBER = new HashSet<SPRW_ARTIST_MEMBER>();
        }
    
        public int USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string CC { get; set; }
        public bool ACT_IND { get; set; }
        public string LAST_MAINT_USER_ID { get; set; }
        public System.DateTime LAST_MAINT_TIME { get; set; }
        public int SALT { get; set; }
    
        public virtual ICollection<SPRW_ARTIST_MEMBER> SPRW_ARTIST_MEMBER { get; set; }
    }
}
